apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app.com.co/env: dev
    app.com.co/project: devsecops
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: test-pod
  template:
    metadata:
      labels:
        app: test
        app.com.co/project: test
    spec:
      automountServiceAccountToken: false